### ISSUE TITLE
UTXO transfer EVM account did not receive funds

### ISSUE THREAD

**Issue by CryptoM77** [MeerLabs/KAHF-wallet-testing-issues#10]
**Description：**
The conversion of 1,186.00 MEER from UTXO to EVM account was successful on the chain, but no corresponding funds were actually received.

**Address, hash details：**

MmKd2H8iT8eifrMYxMc9moNBHD59pENgmzy

0xadd864A694aD77F80d662C6B9ee6b4545db44e1E

f1a9b7407067a7c7e4d7ed7b76aad05efbb2f8efea3a4c27f167c9d73f6724f3

**Relevant Screenshots：**

![20240122-200109](https://github.com/MeerLabs/KAHF-wallet-testing-issues/assets/157371260/7c1068b6-2807-4fe1-bd2a-0c1d8a4c5ce4)

![20240122-200136](https://github.com/MeerLabs/KAHF-wallet-testing-issues/assets/157371260/905bc2da-e42f-4f48-b5f6-78b86026b4fe)

**Comment by jahali6128** [comment]
The address that you listed "0xadd864A..." is not the same as the one which appears on Meerscan block explorer (which begins with "0xAdd0800..."). The address on Meerscan points to this EVM account: https://qng.meerscan.io/address/0xAdd08004469d98C3784C953C1E502D22adb44E1E

**Comment by hehe-max** [comment]
https://meerscan.io/tx/f1a9b7407067a7c7e4d7ed7b76aad05efbb2f8efea3a4c27f167c9d73f6724f3
The transfer has already been made to the account. The transfer is made by oneself, so it will only be displayed in utxo
