### ISSUE TITLE
Unable to Add Currencies Other Than Meer and USDT - Android 

### ISSUE THREAD

**Issue by ShoaibMuni** [MeerLabs/KAHF-wallet-testing-issues#11]
Description:
I am facing an issue where I can only add Meer and USDT in the Android wallet , and other currencies cannot be added.

Steps to Reproduce:

Open the Meer wallet on Android
Attempt to add currencies other than Meer and USDT.
Observe the issue preventing the addition of other currencies.
Expected Behavior:
The wallet on Android, Version 3, should allow the addition of various currencies, not limited to Meer and USDT.

Relevant Screenshots:
![Screenshot_2023-12-15-22-42-48-204_com kahf_app_test](https://github.com/MeerLabs/KAHF-wallet-testing-issues/assets/115460182/8633fc33-49bb-421f-8350-eae4c91dfbb6)

Environment:

OS: Android

**Comment by hehe-max** [comment]
This is search. To add a token, please click on the plus sign on the right side
