### ISSUE TITLE
Anomalies Occurred During Unlocking

### ISSUE THREAD

**Issue by CryptoM77** [MeerLabs/KAHF-wallet-testing-issues#12]
**Specifics:**
When the user attempted to execute the asset transfer from UTXO MEER to EVM MEER, a prompt indicating "Insufficient Balance" was displayed.

Regarding the insufficient balance prompt, a re-verification has been conducted, confirming that an adequate amount of Gas fees has been reserved.

Subsequently, the user clicked the "Unlock" button in the "MEER Check" interface's locked asset section.    Originally, only 3.3508171 MEER were locked, and the usable assets were 80,617.9329 MEER.

However, after clicking the button, the locked assets increased to 80,617.9329 MEER, while the usable assets decreased to 3,350.8171 MEER.

Upon encountering the anomaly, clicking the "Unlock" button again resulted in the interface displaying an address error directly.

**Address：**

- MmfPRsX5kz6n1dsn7UG18Qjz5sT6JVM4Bzs

- 0x11cf91eF7108aCb9aE316e684a0e1B8f9016ECd2

![efbfac86e6bbcd0ebf1f2344fd73d0b](https://github.com/MeerLabs/KAHF-wallet-testing-issues/assets/157371260/14f26c9e-de2a-422e-89f7-be3647c4b8dd)

![188e00a7e8c2eea83677b1ff4f9dade](https://github.com/MeerLabs/KAHF-wallet-testing-issues/assets/157371260/8439d84a-76ea-4e1c-ad80-4916f7c5fb40)

**Comment by ShoaibMuni** [comment]
This should be a display problem, let the user directly transfer try

**Comment by CryptoM77** [comment]
![a74dd4ea86170f7b5e30e04ad1230e5](https://github.com/MeerLabs/KAHF-wallet-testing-issues/assets/157371260/bddb3db4-eb37-4cfb-9f11-c2da6a3c1f05)
Transferable quantity 0

**Comment by CryptoM77** [comment]
![2c6e58c727c2738496b5194fe4b05f7](https://github.com/MeerLabs/KAHF-wallet-testing-issues/assets/157371260/2ab28307-5342-425c-8a99-fe6d0ec43ed5)
Transferable quantity 0
