### ISSUE TITLE
Cross-chain exchange exception

### ISSUE THREAD

**Issue by CryptoM77** [MeerLabs/KAHF-wallet-testing-issues#13]
The user perform a cross-chain exchange from MEER USDT to BSC USDT.   The transaction on the Qitmeer chain shows as successful, however, there has been no record of the transaction on the BSC chain.   As of now, more than 20 hours have elapsed.

**Address：**

- 0x1364cEa4CA0f088e34EB8D5212dDb319fBd1aaFE

- 0x98716796ea04f04D1022A390385cF26350ae65a5

**Hash：**

- 0x3a0fac442427b6739b43eb02ee831336e123dece718984aa497698fbc5077e3d

**Non-test version**

![img_v3_027i_c52c5aab-7f07-4fdf-8a23-3fb4b8902dix](https://github.com/MeerLabs/KAHF-wallet-testing-issues/assets/157371260/6213000b-59df-498a-8fbc-19389e0d080c)

**Comment by hehe-max** [comment]
https://bscscan.com/tx/0x75d1153fcb68fad19a517baf8989d8e063876f8495faf982fba478531bd65c2a
This has been received

**Comment by ShoaibMuni** [comment]
This can be marked as done
