### ISSUE TITLE
Incorrect Display of Transaction Amount in UTXO Historical Transactions - Android, Wallet Version 3

### ISSUE THREAD

**Issue by ShoaibMuni** [MeerLabs/KAHF-wallet-testing-issues#3]
Description:
In the V3 version wallet on Android, I have observed an issue with the transaction amount in the UTXO historical transaction records. The displayed amount is incorrect and includes non-numeric characters.

Steps to Reproduce:

Use the V3 version wallet on Android.
Navigate to the UTXO historical transaction records.
Observe the transaction amount, which is incorrectly displayed and contains non-numeric characters.
Expected Behaviour:
The transaction amount in the UTXO historical transaction records of the V3 version wallet should be correctly displayed, containing only numeric characters.

Wallet Version: V3
Operating System: Android 
Relevant Screenshots:
![972f0e4a6631042452ddb4ef49ac86f](https://github.com/MeerLabs/KAHF-wallet-testing-issues/assets/115460182/702dce92-2a55-4713-bfec-3c905e91937a)

Environment:

OS: Android 
Wallet Version: V3

**Comment by adropofliquid** [comment]
Similar to this, transfer fees display wrong information. We are working on fixing this

### Screenshot
![Image](https://github.com/MeerLabs/KAHF-wallet-testing-issues/assets/74161050/6bc2aa2c-0339-409b-a45e-3f1e5b101708)

**Comment by hehe-max** [comment]
Because there are too many zeros after the decimal point. So refer to the price reduction of AVE.


![Image](https://github.com/MeerLabs/KAHF-wallet-testing-issues/assets/77651454/3f6d65c0-9059-41c4-bf4a-0181eebe1657)

**Comment by adropofliquid** [comment]
Thanks for clarifying that. I will close this issue for now
