### ISSUE TITLE
Incorrect Wallet Address After Importing with Private Key and Unavailable Transfer Function - Wallet Version 3, Android OS

### ISSUE THREAD

**Issue by ShoaibMuni** [MeerLabs/KAHF-wallet-testing-issues#5]
Description:
Upon importing a wallet with a private key in the V3 version on Android, I have encountered two issues: firstly, the wallet address displayed is incorrect, and secondly, the transfer function is no longer available, impeding transaction capabilities.

Steps to Reproduce:

Use the V3 version of the wallet on Android.
Import a wallet using the private key.
Observe that the wallet address displayed is incorrect.
Attempt to use the transfer function.
Expected Behaviour:

After importing with a private key, the wallet address should be correctly displayed.
The transfer function should be available for transactions.
Additional Information:

Wallet Version: V3
Operating System: Android
Relevant Screenshots:
![Screenshot_2023-11-23-17-02-16-00_daa8d9433384448c62d4117d54779568](https://github.com/MeerLabs/KAHF-wallet-testing-issues/assets/115460182/4fd41069-9e1a-464c-9a0a-e7cfd20fabff)

Environment:

OS: Android
Wallet Version: V3

**Comment by adropofliquid** [comment]
It works
