### ISSUE TITLE
High Ping with Node Connection

### ISSUE THREAD

**Issue by ShoaibMuni** [MeerLabs/KAHF-wallet-testing-issues#7]
Description:
I am experiencing consistently high ping when connecting to the node, impacting the performance and responsiveness of the Meer wallet.

Steps to Reproduce:

Open the Meer wallet.
Connect to the node.
Observe the high ping affecting the wallet's performance.
Expected Behavior:
Node connection should have a reasonable and stable ping for optimal wallet performance.
Relevant Screenshots:
![IMG_2852](https://github.com/MeerLabs/KAHF-wallet-testing-issues/assets/115460182/686b7ca7-97b1-4cf1-9934-426fb1f5173d)

Environment:

Wallet Version: V3
Operating System: Android

**Comment by hehe-max** [comment]
No testing network rpc
