### ISSUE TITLE
Subject: Unable to Reach Testnet Link on Android OS - Wallet Version 3

### ISSUE THREAD

**Issue by ShoaibMuni** [MeerLabs/KAHF-wallet-testing-issues#8]
Description:
I am encountering an issue where I am unable to reach the testnet link on the Android OS with Wallet Version 3.

Steps to Reproduce:

Open the Meer wallet on Android, Version 3.
Attempt to access the testnet link.
Observe the issue preventing successful access to the testnet.
Expected Behavior:
The testnet link should be reachable and accessible from the Meer wallet on Android, Version 3.

Wallet Version: Version 3

Relevant Screenshots:
![IMG_20231206_191713_202](https://github.com/MeerLabs/KAHF-wallet-testing-issues/assets/115460182/931300a4-4566-4d57-ba07-6d7ccda71084)

Environment:

OS: Android
Wallet Version: Version 3

**Comment by adropofliquid** [comment]
It works

**Comment by adropofliquid** [comment]
It works
